package playhangman;

import javax.swing.JOptionPane;

public class LogIn_SignUp extends javax.swing.JFrame {
    public static ConsultasBD ok = new ConsultasBD();

    public LogIn_SignUp() {
        initComponents();
        this.setTitle("HANGMAN - Log In or Sign Up");
        this.setLocation(50, 0);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        background = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        Button_LogIn = new javax.swing.JButton();
        Button_SignUp = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt_password = new javax.swing.JPasswordField();
        txt_passwordr = new javax.swing.JPasswordField();
        txt_passwordrr = new javax.swing.JPasswordField();
        txt_fullname = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_usernamer = new javax.swing.JTextField();
        txt_username = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background.jpg"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Full name");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 340, -1, -1));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Your current email address ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 400, -1, -1));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Choose your username ");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Create a password");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 520, -1, -1));

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Confirm your password");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 580, -1, -1));

        Button_LogIn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Button_LogIn.setText("Log In");
        Button_LogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_LogInActionPerformed(evt);
            }
        });
        getContentPane().add(Button_LogIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 150, -1, -1));

        Button_SignUp.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        Button_SignUp.setText("Sign Up  ");
        Button_SignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SignUpActionPerformed(evt);
            }
        });
        getContentPane().add(Button_SignUp, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 570, -1, -1));

        jLabel9.setFont(new java.awt.Font("SimLLHP", 1, 48)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Create your Hangman Account  ");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        jLabel2.setFont(new java.awt.Font("SimLLHP", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sign in with your Hangman Account   ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, -1, -1));

        txt_password.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_password.setText("123456789");
        getContentPane().add(txt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, 120, -1));

        txt_passwordr.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        getContentPane().add(txt_passwordr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 510, 120, -1));

        txt_passwordrr.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        getContentPane().add(txt_passwordrr, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 570, 120, -1));

        txt_fullname.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_fullname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_fullnameKeyTyped(evt);
            }
        });
        getContentPane().add(txt_fullname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 330, 280, -1));

        txt_email.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        getContentPane().add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 390, 280, -1));

        txt_usernamer.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        getContentPane().add(txt_usernamer, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 120, -1));

        txt_username.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        txt_username.setText("victoorm24");
        getContentPane().add(txt_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 120, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Background.jpg"))); // NOI18N
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 700));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SignUpActionPerformed

     
        if(txt_passwordr.getText().compareTo("")==0||txt_fullname.getText().compareTo("")==0 ||txt_email.getText().compareTo("")==0||txt_usernamer.getText().compareTo("")==0){
            JOptionPane.showMessageDialog(this, "No puedes dejar espacios en blanco","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        if(txt_passwordr.getText().compareTo(txt_passwordrr.getText())!=0){
            JOptionPane.showMessageDialog(this, "Las contraseñas no coinciden. ¿Quieres volver a intentarlo?","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
            return;
        } 
       ok.insertar(txt_fullname.getText(), txt_email.getText(), txt_usernamer.getText(), txt_passwordr.getText());
       Sonidos.registro.play();
       JOptionPane.showMessageDialog(this, "Registro Exitoso","AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
       txt_fullname.setText("");
       txt_email.setText("");
       txt_usernamer.setText("");
       txt_passwordr.setText("");
       txt_passwordrr.setText("");
    }//GEN-LAST:event_Button_SignUpActionPerformed

    private void Button_LogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_LogInActionPerformed
     
        if ((ok.buscarUser(txt_username.getText(), txt_password.getText()) != null)) {
          Sonidos.welcome.play();    
          javax.swing.JOptionPane.showMessageDialog(this,"W E L C O M E! \n" + ConsultasBD.UsuarioLogin.getNombre() ,"AVISO!",javax.swing.JOptionPane.INFORMATION_MESSAGE);
          PrincipalV m = new PrincipalV();
          m.setVisible(true);
          this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"El usuario o la contraseña son incorrectos\n Vuelva a intentarlo.", "Error", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_Button_LogInActionPerformed

    private void txt_fullnameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fullnameKeyTyped
      
        char c = evt.getKeyChar();
        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z') && (c < ' ' || c > ' ')) {
            evt.consume();
        }
    }//GEN-LAST:event_txt_fullnameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn_SignUp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn_SignUp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_LogIn;
    private javax.swing.JButton Button_SignUp;
    private javax.swing.JLabel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_fullname;
    private javax.swing.JPasswordField txt_password;
    private javax.swing.JPasswordField txt_passwordr;
    private javax.swing.JPasswordField txt_passwordrr;
    private javax.swing.JTextField txt_username;
    private javax.swing.JTextField txt_usernamer;
    // End of variables declaration//GEN-END:variables
}
